# Site Settings
name: Kol's Korner
title: Kol's Korner ¦ Your cozy corner for AI, tech, science, photography, art,
  and more
description: Welcome to Kol's Korner, an online space dedicated to showcasing a
  diverse array of interests, from artificial intelligence and cutting-edge
  technology to groundbreaking science, mesmerizing photography, and captivating
  art. Join us as we delve into the ever-evolving world of creativity and
  innovation, uncovering new insights, inspirations, and adventures along the
  way.
tags:
  - blog
  - AI
  - technology
  - science
  - photography
  - art
  - artificial-intelligence
  - tech-news
  - design
  - web-development
  - programming
  - robotics
  - space
  - environment
show_hero: true
menu:
  - title: Home
    url: /
  - title: Photography
    url: https://koltregaskesphotography.com/
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml

email: me@koltregaskes.com
# See: https://disqus.com/
disqus_username: 
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xoqzpzog


# Social Media Settings
# Remove the item if you don't need it
github_username: koltregaskes
facebook_username: 
twitter_username: koltregaskes
instagram_username: koltregaskes
linkedin_username: 
medium_username: 


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.koltregaskes.com" # the base hostname & protocol for your site
google_analytics: "368810850"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v3.1.2
